# Generated by Django 4.2.1 on 2023-08-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.TextField(default=0, null=True),
        ),
    ]
