# Generated by Django 4.2.1 on 2023-08-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_account_adminaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='users',
            name='bank',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='adminaccount',
            name='bank',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='adminaccount',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='adminaccount',
            name='number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.TextField(null=True),
        ),
    ]
