# Generated by Django 4.2.1 on 2023-08-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_account_users_bank_users_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='bank_name',
        ),
        migrations.AddField(
            model_name='users',
            name='bank_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.TextField(default=0, null=True),
        ),
    ]
