# Generated by Django 4.2.1 on 2023-08-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_name_users_bank_name_users_bank_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
