# Generated by Django 4.2.1 on 2023-08-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_history_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Histories',
        ),
    ]
