# Generated by Django 4.2.1 on 2023-08-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_history_histories'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='parcent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='plan',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
