# Generated by Django 4.2.1 on 2023-08-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_users_price_alter_plans_price_alter_users_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histories',
            name='user',
        ),
    ]
